### ISSUE TITLE
_common path when moving a task from outside task-editor and GIT

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/task-editor#18]
I am wondering is we move a task from outside task-editor, push to github and refresh in task-editor, do we have to change the _common and maybe other variable path ? 
I remember, for example, that sometimes I get this message when importing:

index.html: Import of this file done.

Corrected possible errors in _common paths.

What possible path may have to be changed other that _common path ?

**Comment by mblockelet** [comment]
Hi, this message will generally appear on Git imports because they don't have the same structure as the SVN, but isn't an issue as, as the message says, svnimport corrects the paths automatically. I kept the message as a confirmation that the Task Importer did detect and fix the _common paths properly, but I should probably remove it as I now see how it can be confusing.

You don't have to change the _common path in the files anyway, as task-editor will regenerate them correctly next time you save the task. But as I said, it's not needed to do it as the Task Importer fixes everything.
