### ISSUE TITLE
Task are not taken into account for the validate button

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/task-editor#27]
Hi Michel, 

I followed you tutorial and I have integrated one task into the cspace structure, but the task doesn't appear into the chapter grading structure. 
PLease see there is 0 assignements into studio. 
https://imt.algorea.org/contents/5807-5802-745723603112028441-943610494122964335/
https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@e9317cf792024f9cbd2d3854d73a2335
![image](https://user-images.githubusercontent.com/19490273/73954580-4c794680-4902-11ea-8108-74279227f714.png)

But there is one task integrated which is this one https://imt.algorea.org/contents/5807-5802-745723603112028441-943610494122964335-1925718034702675433-548574824319546249-1620370338258757999/

Thanks for your help. 
Best,

**Comment by mblockelet** [comment]
Hi,

The chapter validation system was made considering only "leaf chapters" would be integrated as much, which is to say directly the chapters containing the tasks, and not a chapter containing chapters containing chapters etc. ...

For instance, using the URL https://imt.algorea.org/contents/5807-5801-745723603112028441-943610494122964335-1925718034702675433-548574824319546249/ works, because it's a "leaf chapter", but the one you had used, https://imt.algorea.org/contents/5807-5801-745723603112028441-943610494122964335/, doesn't work, because it only contains chapters.

The change to be able to integrate any chapter, not only "leaf" ones, is easy to make ; please tell me if you want me to change the behavior.

**Comment by EllaHa** [comment]
Hi Michel, 

Thanks for your quick answer. The faculty members would like to have one button for one MOOC. So it would be great to have all chapters integrated into the grade policy. 

All the best, 

Ella

**Comment by mblockelet** [comment]
Hello, it has been changed to be able to accomodate integrating any chapter, and displaying the results of the whole subtree of that chapter.
